In [14]:
import AHP
import numpy as np

# 1.创建矩阵

In [69]:
A = np.random.randint(1, 9,[4, 4])
A = A.astype(np.float)
for i in range(4):
    for j in range(i,4):
        if(i == j):
            A[j, i] = 1
        else:
            A[j, i] = 1/A[i,j]
A

array([[1.        , 2.        , 3.        , 5.        ],
       [0.5       , 1.        , 2.        , 5.        ],
       [0.33333333, 0.5       , 1.        , 1.        ],
       [0.2       , 0.2       , 1.        , 1.        ]])

# 2.一致性检验

In [113]:
AAHP = AHP.AHP(A)
WA = AAHP.get_eig()

最大的特征值: 4.1053
对应的特征向量为: [0.806  0.5258 0.2218 0.1572]
归一化后得到权重向量: [0.4711 0.3073 0.1296 0.0919]


In [72]:
AAHP.test_consitst()

判断矩阵的CI值为0.0351
判断矩阵的RI值为0.9
判断矩阵的CR值为0.039，通过一致性检验


True

# 3.层一致性检验

## 3.1.创建并检验AA1

In [89]:
AA1 = np.random.randint(1, 9,[3, 3])
AA1 = AA1.astype(np.float)
for i in range(3):
    for j in range(i,3):
        if(i == j):
            AA1[j, i] = 1
        else:
            AA1[j, i] = 1/AA1[i,j]
AA1

array([[1. , 1. , 2. ],
       [1. , 1. , 1. ],
       [0.5, 1. , 1. ]])

In [115]:
AA1AHP = AHP.AHP(AA1)
WAA1 = AA1AHP.get_eig()

最大的特征值: 3.0536
对应的特征向量为: [0.7024 0.5575 0.4425]
归一化后得到权重向量: [0.4126 0.3275 0.2599]


In [91]:
AA1AHP.test_consitst()

判断矩阵的CI值为0.0268
判断矩阵的RI值为0.58
判断矩阵的CR值为0.0462，通过一致性检验


True

## 3.2.创建并检验AA2

In [98]:
AA2 = np.random.randint(1, 9,[3, 3])
AA2 = AA2.astype(np.float)
for i in range(3):
    for j in range(i,3):
        if(i == j):
            AA2[j, i] = 1
        else:
            AA2[j, i] = 1/AA2[i,j]
AA2

array([[1.   , 8.   , 8.   ],
       [0.125, 1.   , 1.   ],
       [0.125, 1.   , 1.   ]])

In [116]:
AA2AHP = AHP.AHP(AA2)
WAA2 = AA2AHP.get_eig()

最大的特征值: 3.0
对应的特征向量为: [0.9847 0.1231 0.1231]
归一化后得到权重向量: [0.8 0.1 0.1]


In [100]:
AA2AHP.test_consitst()

判断矩阵的CI值为0.0
判断矩阵的RI值为0.58
判断矩阵的CR值为0.0，通过一致性检验


True

## 3.3.创建并检验AA3

In [104]:
AA3 = np.random.randint(1, 9,[3, 3])
AA3 = AA3.astype(np.float)
for i in range(3):
    for j in range(i,3):
        if(i == j):
            AA3[j, i] = 1
        else:
            AA3[j, i] = 1/AA3[i,j]
AA3

array([[1.        , 1.        , 7.        ],
       [1.        , 1.        , 7.        ],
       [0.14285714, 0.14285714, 1.        ]])

In [117]:
AA3AHP = AHP.AHP(AA3)
WAA3 = AA3AHP.get_eig()

最大的特征值: 3.0
对应的特征向量为: [0.7035 0.7035 0.1005]
归一化后得到权重向量: [0.4667 0.4667 0.0667]


In [106]:
AA3AHP.test_consitst()

判断矩阵的CI值为0.0
判断矩阵的RI值为0.58
判断矩阵的CR值为0.0，通过一致性检验


True

## 3.4.创建并检验AA4

In [110]:
AA4 = np.random.randint(1, 9,[3, 3])
AA4 = AA4.astype(np.float)
for i in range(3):
    for j in range(i,3):
        if(i == j):
            AA4[j, i] = 1
        else:
            AA4[j, i] = 1/AA4[i,j]
AA4

array([[1.        , 4.        , 6.        ],
       [0.25      , 1.        , 2.        ],
       [0.16666667, 0.5       , 1.        ]])

In [118]:
AA4AHP = AHP.AHP(AA4)
WAA4 = AA4AHP.get_eig()

最大的特征值: 3.0092
对应的特征向量为: [0.9541 0.2625 0.1445]
归一化后得到权重向量: [0.701  0.1929 0.1062]


In [112]:
AA4AHP.test_consitst()

判断矩阵的CI值为0.0046
判断矩阵的RI值为0.58
判断矩阵的CR值为0.0079，通过一致性检验


True

# 4.计算权重并排序

In [134]:
B = np.zeros([3])
for i in range(3):
    B[i] = WAA1[i]*WA[0] + WAA2[i]*WA[1] + WAA3[i]*WA[2] + WAA4[i]*WA[3]
B

array([0.56512208, 0.26322708, 0.17157299])